# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kargo < Formula
  desc "CLI for Kargo"
  homepage "https://kargo.io"
  version "1.2.0-rc.32"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/krancour/kargo/releases/download/v1.2.0-rc.32/kargo-darwin-amd64"
      sha256 "b27ca948a0dab2a023727d5d836595fe3e3dfdcdc9f69480f590f5a0780ac4b7"

      def install
        bin.install "kargo-darwin-amd64" => "kargo"
      end
    end
    on_arm do
      url "https://github.com/krancour/kargo/releases/download/v1.2.0-rc.32/kargo-darwin-arm64"
      sha256 "504f0bfb5bfe96b35b3fa98bdfbaf0d0db59039bdbfc46f9068f9cf9e954a355"

      def install
        bin.install "kargo-darwin-arm64" => "kargo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/krancour/kargo/releases/download/v1.2.0-rc.32/kargo-linux-amd64"
        sha256 "9abbf5366cfd10894315b0a73a142265e23361d65d36482c6bfb387af7dfb484"

        def install
          bin.install "kargo-linux-amd64" => "kargo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/krancour/kargo/releases/download/v1.2.0-rc.32/kargo-linux-arm64"
        sha256 "a31a5b79fe0b519f53fd3e3a86898b42bfd9acccd4da06b4e9183e3044986d6a"

        def install
          bin.install "kargo-linux-arm64" => "kargo"
        end
      end
    end
  end

  test do
    assert_match "Client Version: v#{version}", shell_output("#{bin}/kargo version --client")
  end
end
