# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Formula/kargo < Formula
  desc "CLI for Kargo"
  homepage "https://kargo.io"
  version "1.2.0-rc.25"
  license "Apache-2.0"
  depends_on :macos

  on_intel do
    url "https://github.com/krancour/kargo/releases/download/v1.2.0-rc.25/kargo-darwin-amd64"
    sha256 "072b3993777063a2913e4d2a85c6ef63d1d9035d094b8dd074caf87a55ed2e21"

    def install
      bin.install "kargo-darwin-amd64" => "kargo"
    end
  end
  on_arm do
    url "https://github.com/krancour/kargo/releases/download/v1.2.0-rc.25/kargo-darwin-arm64"
    sha256 "b2403424ff7305f6b0ee063687dbd8c09417ad2475fe9ec545fe5a28e7d2842e"

    def install
      bin.install "kargo-darwin-arm64" => "kargo"
    end
  end

  test do
    assert_match "Client Version: v#{version}", shell_output("#{bin}/kargo version --client")
  end
end
