# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kargo < Formula
  desc "CLI for Kargo"
  homepage "https://kargo.io"
  version "1.2.0-rc.29"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/krancour/kargo/releases/download/v1.2.0-rc.29/kargo-darwin-amd64"
      sha256 "474fc8d61f803ed54081770b5a1eb25b8c2c5e75d37e41bb22bc6d0832b66d64"

      def install
        bin.install "kargo-darwin-amd64" => "kargo"
      end
    end
    on_arm do
      url "https://github.com/krancour/kargo/releases/download/v1.2.0-rc.29/kargo-darwin-arm64"
      sha256 "803cd8e0c27a67430f48e947ed1e1ceda2cb919d7ba30d281cf8e4a5f12c513e"

      def install
        bin.install "kargo-darwin-arm64" => "kargo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/krancour/kargo/releases/download/v1.2.0-rc.29/kargo-linux-amd64"
        sha256 "fd65734e0e9618e74c1769e8d95e5f3c411db55fe117cdb9b87dd94cba5cf6f5"

        def install
          bin.install "kargo-linux-amd64" => "kargo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/krancour/kargo/releases/download/v1.2.0-rc.29/kargo-linux-arm64"
        sha256 "66155a73309bfeeb31360b6ceb3386d2c3a6094b21b21f162f5334f8d781143e"

        def install
          bin.install "kargo-linux-arm64" => "kargo"
        end
      end
    end
  end

  test do
    assert_match "Client Version: v#{version}", shell_output("#{bin}/kargo version --client")
  end
end
